media_path: /Users/graysonwilson/Desktop
temp_path: ""
original_handling: keep
workers: 3
ffmpeg_path: ffmpeg
ffprobe_path: ffprobe
queue_file: config/queue.json
pushover_user_key:
pushover_app_token:
notify_on_complete: false
